name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: List and Read Files
          run: | 
            echo "My first Github Actions Job"
            ls -lrta
            cat README.md

        # - name: Generate ASCII Artwork
        #   run: cowsay -f yoda "Mind what you have learned. Save you it can" >> yoda.txt

        # - name: List files
        #   run: ls
        
        # - name: Read file
        #   run: cat README.md