name: Generate ASCII Artwork

on: push

jobs:
    build_job_1:
      runs-on: ubuntu-latest
      steps:
    #   - name: Checkout Repo
    #     uses: actions/checkout@v4

      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y

    #   - name: Executing Shell Script
    #     run: |
    #       chmod +x ./ascii-script.sh
    #       ./ascii-script.sh

      - name: Execute Cowsay CMD
        run: cowsay -f tux "Sudo! Give Me Super Power!" >> tux.txt

      - name: Sleep for 30 seconds
        run: sleep 30

    test_job_2:
      runs-on: ubuntu-latest
      steps:
    #   - name: Checkout Repo
    #     uses: actions/checkout@v4

      - name: Sleep for 10 seconds
        run: sleep 10

      - name: Test File Exists
        run: grep -i "Sudo" tux.txt

    deploy_job_3:
      runs-on: ubuntu-latest
      steps:
    #   - name: Checkout Repo
    #     uses: actions/checkout@v4

      - name: Read File
        run: cat tux.txt

    #   - name: Executing Shell Script
    #     run: |
    #         chmod +x ./ascii-script.sh
    #         ./ascii-script.sh