name: Multi-OS Docker Deployment Workflow

on: [push, pull_request, workflow_dispatch]
 
jobs:
    Linux-and-Windows-Deploy:
      strategy:
        fail-fast: false
        max-parallel: 2
        matrix:
          os: [ubuntu-latest, ubuntu-20.04, windows-latest]
          images: [hello-world, alpine]
          exclude:
            - images: alpine
              os: windows-latest
            - images: amd64/alpine
              os: ubuntu-20.04
      runs-on: ${{ matrix.os }}
      steps:
      - name: Echo Docker Details
        run: docker info

      - name: Run Image on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}


    macOS-Deploy:
        needs: Linux-and-Windows-Deploy
        runs-on: macos-latest
        steps:
        - name: Install Docker
          run: |
            brew install --cask docker
            open /Applications/Docker.app
            # Wait for Docker to start
            sleep 60
    
        - name: Echo Docker Details
          run: docker info
    
        - name: Run Image on macOS
          run: docker run hello-world